# Generated by Django 4.2.7 on 2023-12-08 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+989199999933'.", regex='^(\\+98|0)?9\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='user_type',
            field=models.CharField(choices=[('e', 'employee'), ('c', 'customer'), ('m', 'manager')], default='c', max_length=1),
        ),
    ]
