# Generated by Django 4.2.7 on 2023-12-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafemenu', '0002_category_slug_menuitem_slug_alter_menuitem_mojoudi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_img/', verbose_name='category_image'),
        ),
        migrations.AddField(
            model_name='image',
            name='sub_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_item_img/', verbose_name='Menu_Item_Image'),
        ),
    ]
