# Generated by Django 4.2.7 on 2023-12-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafemenu', '0003_remove_image_path_category_sub_image_image_sub_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_item_img/', verbose_name='Menu_Item_Main_Image'),
        ),
    ]
